name: Merge PR on "/shipit" Comment

on:
  issue_comment:
    types:
      - created

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_BRANCH: ${{ github.head_ref || github.ref_name }}
  HEAD: ${{ github.head_ref }}
  REF: ${{ github.ref_name }}
  PULL: ${{ github.event.issue.pull_request }}
  REFNAME: ${{ github.event.issue.pull_request.baseRefName }}


jobs:
  merge-on-shipit:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Comment and Merge
        run: |
          COMMENT=$(jq -r .comment.body $GITHUB_EVENT_PATH)
          
          if [[ "$COMMENT" == "/shipit" ]]; then
            PR_NUMBER=$(jq -r .issue.number $GITHUB_EVENT_PATH)
            TICKET_ID=$(echo $GITHUB_BRANCH | awk -F'/' '{print $2}')
            echo "Merging PR #$PR_NUMBER"
            
            gh pr merge $PR_NUMBER --squash
            
            echo "GITHUB_BRANCH => $GITHUB_BRANCH, TICKET_ID=$TICKET_ID"
            echo "event = $EVENT, pull = $PULL, refname= $REFNAME"
            echo "HEAD => $HEAD, REF=$REF"
            curl -H $JIRA_AUTH -H "Content-Type: application/json" --data '{"transition": {"id": "21"}}' "https://accredible.atlassian.net/rest/api/3/issue/$TICKET_ID/transitions"
          else
            echo "No action needed. Comment is not '/shipit'."
          fi
