name: Merge PR on "/shipit" Comment

on:
  issue_comment:
    types:
      - created

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  merge-on-shipit:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Comment and Merge
        run: |
          COMMENT=$(jq -r .comment.body $GITHUB_EVENT_PATH)
          
          if [[ "$COMMENT" == "/shipit" ]]; then
            PR_NUMBER=$(jq -r .issue.number $GITHUB_EVENT_PATH)
            TICKET_ID=$(gh pr view $PR_NUMBER --json headRefName | jq -r .headRefName)

            echo "Merging PR #$PR_NUMBER"
            gh pr merge $PR_NUMBER --squash

            echo "Setting $TICKET_ID to 'pending-release' status in Jira"
            curl -H $JIRA_AUTH -H "Content-Type: application/json" --data '{"transition": {"id": "21"}}' "https://accredible.atlassian.net/rest/api/3/issue/$TICKET_ID/transitions"
          else
            echo "No action needed. Comment is not '/shipit'."
          fi
